<?php 


function delicious_form_alter($form, $form_state, $form_id) {
	dpm ($form_id, 'This is the form ID: ');
	//dpm ($form_state, 'This is the form state: ');
	//dpm ($form, 'This is the form: ');
}

$comment = 'This is my favorite recipe.';

function delicious_comment_insert($comment) {
	dpm ($comment);
}


/**
 * Implements hook_menu().
 */
function delicious_menu() {
	$items = array();
	// Admin configuration group.
	$items['admin/config/delicious'] = array(
		'title' => 'Delicious Wind Farms',
		'description' => 'Administer Delicious Wind Farms',
		'access arguments' => array('administer delicious wind farms'),			
	);
	
	// Admin configuration - Settings.
	$items['admin/config/windfarms/manage'] = array(
	'title' => 'Delicious Wind Frams settings',
	'description' => 'Manage Delicious Wind Farm settings and configuration.',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('delicious_admin_settings_form'),		
	);
	return $items;
}



/**
 * Implements hook_menu
 */


/**
 * Implements hook_form().
 */
function delicious_form($node, &$form_state) {
	$form['foo'] = array(
			'#type' => 'textfield',
			'#title' => t('bar'),
			'#default_value' => t('foo'),
			'#size' => 60,
			'#maxlength' => 64,
			'#description' => t('baz'),
	);
return $form;	
}
